= el-CICD Chart
:source-highlighter: rouge
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:sectnums:
:toc:

**Status: ALPHA**::

[IMPORTANT]
====
**Feedback is needed and would be appreciated.**

This sub-project is under active development, and a beta release is targeted for fall of 2024.  
====

== Overview

Helm is an excellent packaging and deployment tool, which makes sense given that that is the tool's focus.  What it is not as good at is templating and configuration management.  el-CICD Chart was created to better address these issues.

It offers the following features:

* 100% Helm compatible (**no need for extra plugins**).
* `values.yaml` variables and templates.  **NO** need for Helm templates.
* Configuration management through user-defined deployment profiles.
* Pre-defined Kubernetes resources.

We believe these innovations let Helm do what it does best, while enabling the user to easily, quickly, and concisely create templates and define multiple deployment configurations for Kubernetes and more.

== Documentation

CAUTION: **WORK IN PROGRESS**

link:https://elcicd.github.io/el-CICD-deploy/docs/tutorial/tutorial.html[el-CICD Chart Tutorial,window=read-later]::

link:https://elcicd.github.io/el-CICD-deploy/docs/reference.html[el-CICD Chart Reference Documentation]::

{empty}

== Licensing

el-CICD is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful, but **WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE**.  See the GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to

```
    The Free Software Foundation, Inc.
    51 Franklin Street
    Fifth Floor
    Boston, MA
        02110-1301
```

This document is licensed under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/legalcode). To view a copy of this license, visit

http://creativecommons.org/licenses/by/4.0/

or send a letter to

```
  Creative Commons
  PO Box 1866
  Mountain View, CA
      94042, USA.
```

---

This document is part of the el-CICD project, a complete CICD framework solution for for cloud deployments on Kubernetes

Copyright &#169; {localyear} Evan "Hippy" Slatis
email: hippyod+elcicd -at- gmail -dot- com