=== Free Form Templates

.Features demonstrated
****
* Using free form templates.
* Using el-CICD Chart matrices to deploy copies of the same el-CICD template across namespaces.
****

So far this tutorial has focused on the easy deployments of services using built-in helper el-CICD Chart templates.  Unfortunately, because Kubernetes has many dozens of resources, and it is infinitely extensible with https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/[Custom Resource Definitions,window=read-later] (CRD), creating helper templates for every resource deployable to a Kubernetes cluster is not feasible.

To address this, el-CICD Chart supports templating arbitrary YAML as an el-CICD Chart templates, and in particular Kubernetes resources.  Rather than using a named helper template with `templateName(s)`, the full YAML of the resource is written under the `template` key.  While more verbose than their helper template counterparts, they still allow for the use of el-CICD Chart variables, deployment profiles, and matrices; thus, they will still be able to take advantage of the most powerful features of the el-CICD Chart.

Example use cases for free form templates::
* Any resource without a corresponding el-CICD Chart helper template
* Custom Resource Definitions
+
Many Kubernetes add-ons (e.g. Tekton, Istio, Jaeger, etc.) have CRD's and will therefore not have corresponding el-CICD Chart helper templates.
* General YAML templating
+
Some use cases involve YAML that does not represent a Kubernetes object directly.  Setting the `rawYaml` key on an el-CICD Chart template will prevent el-CICD from trying to generate or look for any `kind`, `apiVersion`, or `metatdata` information.

** Third party chart integration
+
Converting an already working Helm chart may not be feasible and/or is probably not worth the time.  el-CICD Chart can be used as a general YAML templating tool to generate values.yaml files for other Helm charts via Helm https://helm.sh/docs/topics/advanced/#post-rendering[post-renderering].
** Dynamic Kustomizations
+
kustomization.yaml files are very statically declared.  If you need to dynamically generate one, they can also be templated with el-CICD Chart and `kustomize` applied during Helm post-rendering.

[discrete]
==== Create and save the following file as `elcicd-demo-5.yaml`

[source,YAML,linenums]
----
elCicdDefs:
  ENGLISH_JOB: job-en
  ESPANOL_JOB: job-es
  OBJ_NAMES:
  - $<ENGLISH_JOB>
  - $<ESPANOL_JOB>
  ENV:
  - name: WELCOME_MSG
    value: $<WELCOME_MSG>
  JOB_NAMESPACE_2: elcicd-chart-demo-2
  NAMESPACES: # <1>
  - $<HELM_RELEASE_NAMESPACE>
  - $<JOB_NAMESPACE_2>
  COMMAND: ["bash", "-c"]
  JOB_SCRIPT:
  - for COUNTER in {1..5};
    do
        echo ${WELCOME_MSG};
    done

elCicdDefs-$<ENGLISH_JOB>:
  WELCOME_MSG: 'Howdy from $<OBJ_NAME> in release $<HELM_RELEASE_NAME>!'

elCicdDef-$<ESPANOL_JOB>:
  WELCOME_MSG: '¡Hola desde $<OBJ_NAME> en el lanzamiento $<HELM_RELEASE_NAME>!'

elCicdTemplates:
- templateName: namespace
  objName: $<JOB_NAMESPACE_2>

- templateName: job
  objNames: $<OBJ_NAMES>
  namespaces: $<NAMESPACES> # <1>
  objName: $<>-helper # <2>
  image: quay.io/centos/centos:stream9-minimal
  command: $<COMMAND>
  args: $<JOB_SCRIPT>
  env: $<ENV> # <4>

- objNames: $<OBJ_NAMES>
  namespaces: $<NAMESPACES> # <1>
  objName: $<>-raw # <2>
  template: # <3>
    apiVersion: batch/v1
    kind: Job
    spec:
      template:
        spec:
          containers:
          - name: $<OBJ_NAME>
            image: quay.io/centos/centos:stream9-minimal
            command: $<COMMAND>
            args: $<JOB_SCRIPT>
            env: $<ENV> # <4>
          restartPolicy: Never
----

<1> Like `objNames`, `namespaces` is an el-CICD Chart matrix.
+
Each element in the `namespaces` list will generate a copy of the el-CICD Chart template, and assign the value to `.metadata.namespace`.
<2> Both `objNames` and `namespaces` can use patterns to further decorate the final matrix values.
.. $<> refers the element in the matrix; e.g. job-en`.
.. $<#> refers to the index of the element in the matrix; e.g. the pattern `$<>-$<#>` would generate `job-en-1` and `job-en-2`.
.. In the deployment definition above, the __base name__ is decorated with either `-helper` or `-raw` so the pods generated from either the helper template or the raw YAML templates can be identified on site.
.. In templates generated from matrices with patterns, use `$<BASE_OBJ_NAME>` to refer to the undecorated element from the list that generated `$<OBJ_NAME>`.
<3> The `template` helper attribute marks the start of the YAML defining any arbitrary YAML to be deployed to Kubernetes.
.. Matrices, variables, and deployment profiles can be used as usual with free form el-CICD Chart template.
.. The `metadata` section is optional in a free form template.
... el-CICD Chart will attempt generate a `metadata` automatically if it is missing.
... If `rawYaml: true` is set on the el-CICD Chart template, the metadata section will not be generated if missing.
<4> Defining environment variables in a container is the same whether using helper or raw templates.

NOTE: There is never a reason to use a raw template when deploying any Kubernetes resource workload (e.g. Deployment, Pod, Job, etc.) to a cluster.  All of them have helper templates.  This example is for demonstration purposes only.

[discrete]
==== Tutorial steps
:helm-update-command: helm upgrade --install --atomic --history-max=0 -n elcicd-chart-demo --create-namespace -f elcicd-demo-5.yaml elcicd-chart-demo elcicd-charts/elcicd-chart
:helm-manifest-file: free-form-templates-manifest
:kubectl-get-file: free-form-templates-kubectl-get

.What to expect
****
* A second namespace will be created from a namespace helper template, and managed by Helm.
* Using a `job` el-CICD Chart helper template, four Jobs (two per namespace) will be deployed on the cluster, based on two `objNames` and two `namespaces`.
* Using a `job` el-CICD Chart free form template, four Jobs (two per namespace) will be deployed on the cluster, based on two `objNames` and two `namespaces`.
* All Job containers will be created from a simple CentOS 9 Stream minimal image.
* The manifests between all eight Jobs deployed will be identical **except** for `metadata.name`, `metadata.namespace`, and the `WELCOME_MSG` value.
* Each Job Pod will log a few welcome messages based on the environment variable set in the Pod before completing, either in English or Spanish, based on their object names.
****

. {empty}
include::general-steps/upgrade-install-chart.adoc[]

. {empty}
include::general-steps/view-chart-manifests.adoc[]

. {empty}
include::general-steps/view-running-resources.adoc[]

+
:kubectl-get-file: free-form-templates-kubectl-get-2
+
. View the running `elcicd-chart-demo-2` resources in the cluster:
+
```
$ kubectl get -n elcicd-chart-demo-2 deploy,rs,pod,cm,service,ingress
```

Output::
+
```
include::general-steps/kubectl-gets/{kubectl-get-file}.adoc[]
```

. Check the logs of the Jobs:
+
NOTE: Only two of the eight jobs are displayed for brevity.
+
```
$ $ oc logs -f -n elcicd-chart-demo job-en-helper-5c4bb 
```

Output::
+
```
Howdy from job-en-helper in release elcicd-chart-demo!
Howdy from job-en-helper in release elcicd-chart-demo!
Howdy from job-en-helper in release elcicd-chart-demo!
Howdy from job-en-helper in release elcicd-chart-demo!
Howdy from job-en-helper in release elcicd-chart-demo!
```

+
```
$ oc logs -f -n elcicd-chart-demo-2 job-es-raw-bbpjg 
```

Output::
+
```
¡Hola desde job-es-helper en el lanzamiento elcicd-chart-demo!
¡Hola desde job-es-helper en el lanzamiento elcicd-chart-demo!
¡Hola desde job-es-helper en el lanzamiento elcicd-chart-demo!
¡Hola desde job-es-helper en el lanzamiento elcicd-chart-demo!
¡Hola desde job-es-helper en el lanzamiento elcicd-chart-demo!
```

. {empty}
include::general-steps/uninstall-chart.adoc[]
