apiVersion: v1
entries:
  elcicd-chart:
  - apiVersion: v2
    created: "2026-06-26T20:08:08.870742228Z"
    dependencies:
    - name: elcicd-lib
      repository: file://../elcicd-lib
      version: 0.1.0
    description: 'An all-in-one chart meant with the ability to define variables and
      deployment profiles in values.yml files. '
    digest: b58c864495a93a66d7e3c5ef2012087edefcfe505481744ba638cc16beabc1db
    keywords:
    - values.yml
    - parameterized
    - profiles
    - deployment profiles
    - variables
    name: elcicd-chart
    type: application
    urls:
    - elcicd-chart-0.1.0.tgz
    version: 0.1.0
  elcicd-lib:
  - apiVersion: v2
    created: "2026-06-26T20:08:08.871543875Z"
    description: 'An all-in-one library chart meant to be added as a dependency for
      enabling variables and deployment profiles in values.yml files. '
    digest: bc391825ea0c071836174ad583999e8e79556d0c40ea8baf94ff5e0edd6b35ea
    keywords:
    - values.yml
    - parameterized
    - profiles
    - deployment profiles
    - variables
    name: elcicd-lib
    sources:
    - https://github.com/elcicd/el-CICD-deploy/tree/main/charts
    type: library
    urls:
    - elcicd-lib-0.1.0.tgz
    version: 0.1.0
generated: "2026-06-26T20:08:08.869739653Z"
