apiVersion: v1
entries:
  elcicd-chart:
  - apiVersion: v2
    created: "2026-07-24T20:35:52.386161466Z"
    dependencies:
    - name: elcicd-lib
      repository: file://../elcicd-lib
      version: 0.1.0
    description: 'An all-in-one chart meant with the ability to define variables and
      deployment profiles in values.yml files. '
    digest: 56bc61d5158085deaefd07cfa72c15703d0e41e033a7ac4c70f44b72e2852b3d
    keywords:
    - values.yml
    - parameterized
    - profiles
    - deployment profiles
    - variables
    name: elcicd-chart
    type: application
    urls:
    - elcicd-chart-0.1.0.tgz
    version: 0.1.0
  elcicd-lib:
  - apiVersion: v2
    created: "2026-07-24T20:35:52.386958587Z"
    description: 'An all-in-one library chart meant to be added as a dependency for
      enabling variables and deployment profiles in values.yml files. '
    digest: ca0392c5f39578b5a3e844837174d7c5c4e5c7a79e5e2d6ac901d6ef9cf8eb9d
    keywords:
    - values.yml
    - parameterized
    - profiles
    - deployment profiles
    - variables
    name: elcicd-lib
    sources:
    - https://github.com/elcicd/el-CICD-deploy/tree/main/charts
    type: library
    urls:
    - elcicd-lib-0.1.0.tgz
    version: 0.1.0
generated: "2026-07-24T20:35:52.385060867Z"
