apiVersion: v1
entries:
  elcicd-chart:
  - apiVersion: v2
    created: "2026-06-27T00:02:56.894850322Z"
    dependencies:
    - name: elcicd-lib
      repository: file://../elcicd-lib
      version: 0.1.0
    description: 'An all-in-one chart meant with the ability to define variables and
      deployment profiles in values.yml files. '
    digest: 51689844453fb34d9fac40c8c2352eeb26181ecb059b0435bda7f3cb45962973
    keywords:
    - values.yml
    - parameterized
    - profiles
    - deployment profiles
    - variables
    name: elcicd-chart
    type: application
    urls:
    - elcicd-chart-0.1.0.tgz
    version: 0.1.0
  elcicd-lib:
  - apiVersion: v2
    created: "2026-06-27T00:02:56.896033294Z"
    description: 'An all-in-one library chart meant to be added as a dependency for
      enabling variables and deployment profiles in values.yml files. '
    digest: 32115bce513178e9328c8f45e8f16be3a231996a8e4f80504c5350d1fcc7b7c7
    keywords:
    - values.yml
    - parameterized
    - profiles
    - deployment profiles
    - variables
    name: elcicd-lib
    sources:
    - https://github.com/elcicd/el-CICD-deploy/tree/main/charts
    type: library
    urls:
    - elcicd-lib-0.1.0.tgz
    version: 0.1.0
generated: "2026-06-27T00:02:56.893860821Z"
